### ISSUE TITLE
Fix 3 Maintainability issues in multiple files

### ISSUE THREAD

**Issue by Loule95450** [CodingFactory-Repos/Coding-Tools#1]
[CodeFactor](https://www.codefactor.io/repository/github/codingfactory-repos/coding-tools/overview/main) found multiple issues last seen at 99fa2e1711b62cb5152a6c2b361f6ffff62d0806:

#### &#39;next&#39; is defined but never used.
- [ ]  [back-end\app.js:31](https://www.codefactor.io/repository/github/codingfactory-repos/coding-tools/source/main/back-end/app.js#L31)
- [ ]  [back-end\routes\users.js:5](https://www.codefactor.io/repository/github/codingfactory-repos/coding-tools/source/main/back-end/routes/users.js#L5)
- [ ]  [back-end\routes\index.js:5](https://www.codefactor.io/repository/github/codingfactory-repos/coding-tools/source/main/back-end/routes/index.js#L5)

**Comment by Maghwyn** [comment]
Project refractored, closing.
